services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: billingApplication
      POSTGRES_PASSWORD: billingAppPassword
      POSTGRES_DB: billsDatabase
    volumes:
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3456:5432"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "6543:5150"
    depends_on:
      - db
    environment:
    #TODO: Why ist this using the values mentioned up there to build this properly? This is redudancy!
      DATABASE_URL: postgresql://billingApplication:BillingAppPassword@db:5432/bills
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: 5150
      

volumes:
  postgres_data: