services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: billingApplication
      POSTGRES_PASSWORD: billingAppPassword
      POSTGRES_DB: billsDatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3456:5432"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "6543:5150"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://billingApplication:billingAppPassword@db:5432/billsDatabase
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: 5150
      API_KEY: ${API_KEY}

volumes:
  postgres_data:
